# ctest から呼ぶ: tools/parity の pytest を回す。Python か依存が無い環境では「スキップ」(ctest 側で SKIP_REGULAR_EXPRESSION)。
#   cmake -DPARITY_DIR=<tools/parity> -P run_pytests.cmake
if(NOT PARITY_DIR)
    message(FATAL_ERROR "PARITY_DIR が要る")
endif()
set(_py "")
foreach(_c "${PARITY_DIR}/.venv/Scripts/python.exe" "${PARITY_DIR}/.venv/bin/python")
    if(EXISTS "${_c}")
        set(_py "${_c}")
        break()
    endif()
endforeach()
if(NOT _py)
    find_program(_py NAMES python python3)
endif()
if(NOT _py)
    message("PARITY_SKIP: Python が見つからない(tools/parity/setup.ps1 で venv を作ると走る)")
    return()
endif()
execute_process(COMMAND "${_py}" -c "import numpy, scipy, PIL, skimage, flip_evaluator, jsonschema, pytest"
                RESULT_VARIABLE _r OUTPUT_QUIET ERROR_QUIET)
if(NOT _r EQUAL 0)
    message("PARITY_SKIP: 依存が足りない(pwsh tools/parity/setup.ps1 で入る): ${_py}")
    return()
endif()
execute_process(COMMAND "${_py}" -m pytest -q "${PARITY_DIR}/tests"
                WORKING_DIRECTORY "${PARITY_DIR}" RESULT_VARIABLE _r)
if(NOT _r EQUAL 0)
    message(FATAL_ERROR "tools/parity の pytest が失敗(終了コード ${_r})")
endif()
